!include ./theme.pu
'''
'''
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v7.0/dist
!includeurl AWSPuml/AWSCommon.puml
!includeurl AWSPuml/AWSSimplified.puml

' !includeurl AWSPuml/General/User.puml
' !includeurl AWSPuml/General/Users.puml
!includeurl AWSPuml/Compute/Lambda.puml
' !includeurl AWSPuml/Compute/Fargate.puml
!includeurl AWSPuml/Storage/S3Bucket.puml
' !includeurl AWSPuml/Storage/S3Object.puml
' !includeurl AWSPuml/Database/RDS.puml
' !includeurl AWSPuml/Database/RDSPostgreSQLinstance.puml
' !includeurl AWSPuml/Analytics/Kinesis.puml
' !includeurl AWSPuml/GroupIcons/StepFunction.puml
!includeurl AWSPuml/ManagementAndGovernance/CloudWatch.puml
' !includeurl AWSPuml/ManagementAndGovernance/CloudWatchEventEventBased.puml
' !includeurl AWSPuml/ManagementAndGovernance/CloudWatchEventTimeBased.puml
' !includeurl AWSPuml/NetworkingAndContentDelivery/APIGatewayEndpoint2.puml
' !includeurl AWSPuml/Database/DynamoDBTable.puml
' !includeurl AWSPuml/Database/DynamoDBItem.puml
' !includeurl AWSPuml/ApplicationIntegration/SQSQueue.puml
!includeurl AWSPuml/Analytics/KinesisDataFirehose.puml
' !includeurl AWSPuml/Database/DocumentDBwithMongoDBcompatibility.puml
